# Generated by Django 3.2.8 on 2021-10-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nifty',
            new_name='Position',
        ),
    ]
