# Generated by Django 3.2.8 on 2021-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_rename_nifty_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prev_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('turnover', models.DecimalField(decimal_places=8, max_digits=8)),
                ('trade_quantity', models.IntegerField()),
                ('ltp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('perChange', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
