# Generated by Django 3.2.8 on 2021-10-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20211027_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gainer',
            name='perChange',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='gainer',
            name='turnover',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
